name: zdm_crawler

on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 检出代码
    - uses: actions/checkout@v3
      with:
        # 使用 GitHub 默认提供的 token
        token: ${{ secrets.GITHUB_TOKEN }}
    # 配置 Git 用户信息
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    # 设置 JDK 环境
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    # 使用 Maven 构建项目
    - name: Build with Maven
      run: |
        mvn package
        cp ./target/zdm-0.0.1.jar ./zdm.jar
    # 执行主逻辑
    - name: main logic
      env:
        maxPageSize: 20
        minVoted: 10
        minComments: 10
        MIN_PUSH_SIZE: 40
        emailHost: smtp.qq.com
        emailPort: 465
        emailAccount: 599764916@qq.com
        emailPassword: fnkbdckmrmmhbbfe
        spt: ${{ secrets.spt }}
        detail: false
      run: java -jar zdm.jar
    # 添加文件到暂存区
    - name: git add files
      run: |
        git add .
    # 提交更改
    - name: git commit
      run: |
        git commit -m "update articles" || echo "No changes to commit"
    # 推送更改
    - name: git push
      run: |
        git push origin main
